server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5434/notification
    password: pass
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka