server:
  port: 8081
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: fraud
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5434/fraud
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka